Repository dizzpy/Greenie-Web, pull requests merged in 2025-05, with the labels that each got.

#81 feat(profile) Add order history
  src/[features]/auth/pages/ProfilePage.jsx
  src/assets/profile/cccc.png
Labels: bug, enhancement

#82 Fix: Issues in profile management
  package-lock.json
  package.json
  src/[features]/auth/Components/profile/ProfileHeader.jsx
  src/[features]/auth/pages/EditProfilePage.jsx
  src/[features]/auth/pages/ProfilePage.jsx
  src/[features]/feed/components/Poster.jsx
  src/assets/profile/ccccxqwxx.png
  src/config/api.config.js
Labels: fix

#83 fix: update profile management
  src/[features]/auth/Components/profile/ProfileHeader.jsx
  src/[features]/auth/pages/EditProfilePage.jsx
  src/[features]/feed/components/Poster.jsx
  src/assets/profile/Cover-2.png
  src/assets/profile/Cover.png
  src/assets/profile/profileImg.png
Labels: fix

#95 Fix: errors in feed
  index.html
  public/FavGreenie.svg
  src/[features]/feed/components/ChallengeCard.jsx
  src/[features]/feed/components/ChallengeCardSkeleton.jsx
  src/[features]/feed/components/ChallengeList.jsx
  src/[features]/feed/components/PostSkeleton.jsx
  src/[features]/feed/components/Poster.jsx
  src/[features]/feed/pages/Feed.jsx
Labels: fix

#103 fix(feed): fixed challenge section preview
  src/[features]/feed/components/ChallengeList.jsx
  src/[features]/feed/components/ChallengePreviewModal.jsx
Labels: fix

#94 feat(navbar) notification frontend #93
  package-lock.json
  src/[features]/auth/pages/ProfilePage.jsx
  src/components/Shared/NavBar.jsx
Labels: enhancement, feat
